// src/components/sections/ConfigSection.vue
<template>
    <div class="section-background">
        <div class="section-title">
            <font-awesome-icon icon="wrench"/> {{ $t('config_section.config') }}
        </div>
        <div class="section-content grid-cols-5">
            <div>
                <h5 class="section-heading">{{ $t('config_section.path') }}</h5>
                <h2 v-html="isEmpty(data.namelessmc.config.path, true)"></h2>
            </div>
            <div>
                <h5 class="section-heading">{{ $t('config_section.friendly_urls') }}</h5>
                <h2 v-html="booleanBadge(data.namelessmc.config.friendly)"></h2>
            </div>
            <div>
                <h5 class="section-heading">{{ $t('config_section.force_https') }}</h5>
                <h2 v-html="booleanBadge(data.namelessmc.config.force_https)"></h2>
            </div>
            <div>
                <h5 class="section-heading">{{ $t('config_section.force_www') }}</h5>
                <h2 v-html="booleanValue(data.namelessmc.config.force_www)"></h2>
            </div>
            <div>
                <h5 class="section-heading">{{ $t('config_section.trusted_proxies') }}</h5>
                <h2 v-html="isEmpty(data.namelessmc.settings.trusted_proxies, true)"></h2>
            </div>
        </div>
    </div>
</template>

<script>
export default {
    props: [
        'data',
    ],
}
</script>

// src/components/sections/ConfigSection.tsx
import SimpleSection from "../SimpleSection";
import {SectionContent} from "../../types/SectionContent";
import {DebugData} from "../../types/DebugData";
import {useTranslation} from "react-i18next";
import {booleanBadge, isEmpty} from "../../utils";
import {faWrench} from "@fortawesome/free-solid-svg-icons";

interface Props {
    debugData: DebugData;
}

function ConfigSection({
    debugData,
}: Props) {

    const { t } = useTranslation();

    const content: SectionContent[] = [
        {
            header: t('config_section.path'),
            body: isEmpty(debugData.namelessMc.config.core.path, true),
        },
        {
            header: t('config_section.friendly_urls'),
            body: booleanBadge(debugData.namelessMc.config.core.friendly),
        },
        {
            header: t('config_section.force_https'),
            body: booleanBadge(debugData.namelessMc.config.core.forceHttps),
        },
        {
            header: t('config_section.force_www'),
            body: booleanBadge(debugData.namelessMc.config.core.forceWww),
        },
        {
            header: t('config_section.trusted_proxies'),
            body: isEmpty(debugData.namelessMc.settings.trustedProxies, true),
        }
    ]

    return (
        <SimpleSection icon={faWrench} title={t('config_section.config')} content={content} />
    )
}

export default ConfigSection;
