// src/components/sections/GroupsSection.tsx
import {DebugData} from "../../types/DebugData";
import {TableColumnHeader, TableEmptyState, TableProps, TableRow} from "../Table";
import SimpleTableSection from "../SimpleTableSection";
import {faAddressBook} from "@fortawesome/free-solid-svg-icons";
import BooleanBadge from "../utils/BooleanBadge";
import BooleanValue from "../utils/BooleanValue";
import Code from "../utils/Code";

interface Props {
    debugData: DebugData;
}

function GroupsSection({
    debugData,
}: Props) {

    const tableColumnHeaders: TableColumnHeader[] = [
        {
            key: 'groups_section.id',
            classes: ['w-1/12'],
        },
        {
            key: 'groups_section.name',
            classes: ['w-1/6'],
        },
        {
            key: 'groups_section.group_html',
        },
        {
            key: 'groups_section.can_view_staff_cp',
            classes: ['w-1/12'],
        },
        {
            key: 'groups_section.staff',
            classes: ['w-1/12'],
        },
        {
            key: 'groups_section.default',
            classes: ['w-1/12'],
        },
        {
            key: 'groups_section.order',
            classes: ['w-1/12'],
        },
        {
            key: 'groups_section.force_tfa',
            classes: ['w-1/12'],
        }
    ];

    const tableRows: TableRow[] = [];
    for (const [groupId, group] of Object.entries(debugData.namelessmc.groups)) {
        tableRows.push({
            cells: [
                {
                    body: groupId,
                },
                {
                    body: group.name,
                },
                {
                    body: <Code value={group.group_html} />,
                },
                {
                    body: <BooleanValue value={group.admin_cp} />,
                },
                {
                    body: <BooleanValue value={group.staff} />,
                },
                {
                    body: <BooleanValue value={group.default_group} />,
                },
                {
                    body: group.order,
                },
                {
                    body: <BooleanBadge value={group.force_tfa} />,
                }
            ]
        });
    }

    const emptyState: TableEmptyState = {
        textKey: 'groups_section.no_groups',
    }

    const table: TableProps = {
        columnHeaders: tableColumnHeaders,
        rows: tableRows,
        emptyState: emptyState,
    }

    return (
        <SimpleTableSection icon={faAddressBook} titleKey={'groups_section.groups'} table={table} />
    )
}

export default GroupsSection;

// src/components/sections/GroupsSection.vue
<template>
  <div class="section-background">
    <div class="section-title">
      <font-awesome-icon icon="address-book"/> {{ $t('groups_section.groups') }}
    </div>
    <div class="section-content mx-4">
      <table class="table-container">
        <tr>
          <th class="table-title w-1/12">{{ $t('groups_section.id') }}</th>
          <th class="table-title w-1/6">{{ $t('groups_section.name') }}</th>
          <th class="table-title">{{ $t('groups_section.group_html') }}</th>
          <th class="table-title w-1/12">{{ $t('groups_section.can_view_staff_cp') }}</th>
          <th class="table-title w-1/12">{{ $t('groups_section.staff') }}</th>
          <th class="table-title w-1/12">{{ $t('groups_section.default') }}</th>
          <th class="table-title w-1/12">{{ $t('groups_section.order') }}</th>
          <th class="table-title w-1/12">{{ $t('groups_section.force_tfa') }}</th>
        </tr>
        <template v-if="Object.keys(this.data.namelessmc.groups).length > 0">
          <tr v-for="group in this.data.namelessmc.groups" :key="group">
            <td class="table-data">{{ group.id }}</td>
            <td class="table-data">{{ group.name }}</td>
            <td class="table-data" v-html="asCode(group.group_html, true)"></td>
            <td class="table-data" v-html="booleanValue(group.admin_cp)"></td>
            <td class="table-data" v-html="booleanValue(group.staff)"></td>
            <td class="table-data" v-html="booleanValue(group.default_group)"></td>
            <td class="table-data">{{ group.order }}</td>
            <td class="table-data" v-html="booleanBadge(group.force_tfa)"></td>
          </tr>
        </template>
        <tr v-else>
          <td class="table-data" colspan="8">
            <i>{{ $t('groups_section.no_groups') }}</i>
          </td>
        </tr>
      </table>
    </div>
  </div>
</template>

<script>
export default {
  props: [
    'data',
  ],
}
</script>
