// src/components/sections/GroupSyncSection.tsx
import {DebugData} from "../../types/DebugData";
import FloatingSection, {FloatingContent} from "../FloatingSection";
import {faSyncAlt} from "@fortawesome/free-solid-svg-icons";
import {goToModule} from "../../utils";
import BooleanBadge from "../utils/BooleanBadge";
import Empty from "../utils/Empty";

interface Props {
    debugData: DebugData;
}

function GroupSyncSection({
    debugData
}: Props) {

    const injectorsFloatingContent: FloatingContent = {
        subheadingKey: 'group_sync_section.injectors',
        table: {
            columnHeaders: [
                {
                    key: 'group_sync_section.name',
                },
                {
                    key: 'group_sync_section.enabled',
                    classes: ['w-1/6'],
                },
                {
                    key: 'group_sync_section.module',
                }
            ],
            rows: debugData.namelessmc.settings.group_sync.injectors.map(injector => {
                return {
                    cells: [
                        {
                            body: injector.name,
                            title: injector.column_name,
                        },
                        {
                            body: <BooleanBadge value={injector.enabled} />,
                        },
                        {
                            body: injector.module,
                            classes: ['hover:underline', 'cursor-pointer'],
                            click: () => goToModule(injector.module),
                        }
                    ]
                }
            }),
        },
    };

    const rulesFloatingContent: FloatingContent = {
        subheadingKey: 'group_sync_section.rules',
        table: {
            columnHeaders: [
                {
                    key: 'ID',
                    classes: ['w-1/6'],
                },
                ...debugData.namelessmc.settings.group_sync.injectors.map(injector => {
                    return {
                        key: injector.name,
                    };
                })
            ],
            rows: Object.values(debugData.namelessmc.settings.group_sync.rules).map(rule => {
                return {
                    cells: [
                        {
                            body: rule.id,
                        },
                        ...debugData.namelessmc.settings.group_sync.injectors.map(injector => {
                            const group_id = rule[injector.column_name];
                            if (injector.column_name === 'website_group_id') {
                                return {
                                    body: Object.values(debugData.namelessmc.groups).find(g => String(g.id) === group_id)?.name ?? '',
                                };
                            } else {
                                return {
                                    body: <Empty value={group_id} />,
                                };
                            }
                        })
                    ]
                }
            }),
            emptyState: {
                textKey: 'group_sync_section.no_rules',
            }
        }
    }

    return (
        <FloatingSection icon={faSyncAlt} titleKey={'group_sync_section.group_sync'} floatingContent={[injectorsFloatingContent, rulesFloatingContent]} />
    )
}

export default GroupSyncSection;

// src/components/sections/GroupSyncSection.vue
<template>
    <div class="section-title-floating">
        <font-awesome-icon icon="sync-alt"/> {{ $t('group_sync_section.group_sync') }}
    </div>
     <div class="pt-2 mb-8 grid gap-4 lg:grid-cols-2 md:grid-cols-1">
        <div class="section-content-floating">
            <h3 class="section-subheading">{{ $t('group_sync_section.injectors') }}</h3>
            <table class="table-container">
                <tr>
                    <th class="table-title">{{ $t('group_sync_section.name') }}</th>
                    <th class="table-title w-1/6">{{ $t('group_sync_section.enabled') }}</th>
                    <th class="table-title">{{ $t('group_sync_section.module') }}</th>
                </tr>
                <tr v-for="injector in this.injectors()" :key="injector">
                    <td class="table-data" :title="injector.column_name">
                        {{ injector.name }}
                    </td>
                    <td v-html="booleanBadge(injector.enabled)"/>
                    <td class="table-data hover:underline cursor-pointer" @click="goToModule(injector.module)">
                        {{ injector.module }}
                    </td>
                </tr>
            </table>
        </div>
        <div class="section-content-floating">
            <h3 class="section-subheading">{{ $t('group_sync_section.rules') }}</h3>
            <table class="table-container">
                <tr>
                    <th class="table-title w-1/6">ID</th>
                    <th v-for="injector in this.injectors()" :key="injector" class="table-title">
                        {{ injector.name }}
                    </th>
                </tr>
                <template v-if="Object.keys(this.data.namelessmc.settings.group_sync.rules).length > 0">
                    <tr v-for="rule in this.data.namelessmc.settings.group_sync.rules" :key="rule">
                      <td class="table-data">
                        {{ rule.id }}
                      </td>
                      <td v-for="injector in this.injectors()" :key="injector" class="table-data">
                          <span v-if="injector.column_name === 'website_group_id'" :title="rule[injector.column_name]">
                              {{ this.getWebsiteGroupName(rule[injector.column_name]) }}
                          </span>
                        <span v-else v-html="isEmpty(rule[injector.column_name])"></span>
                      </td>
                    </tr>
                </template>
                <tr v-else>
                    <td class="table-data" colspan="4">
                      <i>{{ $t('group_sync_section.no_rules') }}</i>
                    </td>
                </tr>
            </table>
        </div>
     </div>
</template>

<script>
export default {
    props: [
        'data',
    ],
    methods: {
        injectors() {
            return this.data.namelessmc.settings.group_sync.injectors;
        },
        getWebsiteGroupName(id) {
            return this.data.namelessmc.groups[id].name;
        },
    }
}
</script>
