// src/components/sections/IntegrationsSection.tsx
import SimpleTableSection from "../SimpleTableSection";
import {faPlug} from "@fortawesome/free-solid-svg-icons";
import {DebugData} from "../../types/DebugData";
import {booleanBadge, booleanValue} from "../../utils";
import {TableProps} from "../Table";

interface Props {
    debugData: DebugData;
}

function IntegrationsSection({
    debugData,
}: Props) {

    const table: TableProps = {
        columnHeaders: [
            {
                key: 'integrations_section.name',
            },
            {
                key: 'integrations_section.enabled',
            },
            {
                key: 'integrations_section.can_unlink',
            },
            {
                key: 'integrations_section.required',
            },
        ],
        rows: Object.values(debugData.namelessmc.integrations).map(integration => {
            return {
                cells: [
                    {
                        body: integration.name,
                    },
                    {
                        body: booleanBadge(integration.enabled),
                    },
                    {
                        body: booleanValue(integration.can_unlink),
                    },
                    {
                        body: booleanValue(integration.required),
                    },
                ],
            }
        }),
        emptyState: {
            textKey: 'integrations_section.no_integrations',
        },
    }

    return (
        <SimpleTableSection icon={faPlug} titleKey={'integrations_section.integrations'} table={table} />
    )
}

export default IntegrationsSection;

// src/components/sections/IntegrationsSection.vue
<template>
  <div class="section-background">
    <div class="section-title">
      <font-awesome-icon icon="plug"/> {{ $t('integrations_section.integrations') }}
    </div>
    <div class="section-content">
      <table class="table-container mx-4">
        <tr>
          <th class="table-title">{{ $t('integrations_section.name') }}</th>
          <th class="table-title">{{ $t('integrations_section.enabled') }}</th>
          <th class="table-title">{{ $t('integrations_section.can_unlink') }}</th>
          <th class="table-title">{{ $t('integrations_section.required') }}</th>
        </tr>
        <template v-if="Object.keys(this.data.namelessmc.integrations).length > 0">
          <tr v-for="integration in this.data.namelessmc.integrations" :key="integration">
            <td class="table-data">{{ integration.name }}</td>
            <td class="table-data" v-html="booleanBadge(integration.enabled)"></td>
            <td class="table-data" v-html="booleanValue(integration.can_unlink)"></td>
            <td class="table-data" v-html="booleanValue(integration.required)"></td>
          </tr>
        </template>
        <tr v-else>
          <td class="table-data" colspan="4">
            <i>{{ $t('integrations_section.no_integrations') }}</i>
          </td>
        </tr>
      </table>
    </div>
  </div>
</template>

<script>
export default {
  props: [
    'data',
  ],
}
</script>
