// src/components/sections/LogsSection.tsx
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {useTranslation} from "react-i18next";
import SyntaxHighlighter from "react-syntax-highlighter";
import {githubGist} from "react-syntax-highlighter/dist/cjs/styles/hljs";
import {DebugData} from "../../types/DebugData";
import githubDarkDimmed from "../../theme/github-dark-dimmed";
import {faFilePen} from "@fortawesome/free-solid-svg-icons";

interface Props {
    debugData: DebugData;
}

function LogsSection({
    debugData,
}: Props) {

    const { t } = useTranslation();

    const theme = localStorage.getItem('nmc-debug-theme') ?? 'light'

    const logs = [
        {
            titleKey: 'logs_section.fatal_log',
            content: debugData.logs.fatal
        },
        {
            titleKey: 'logs_section.warning_log',
            content: debugData.logs.warning
        },
        {
            titleKey: 'logs_section.notice_log',
            content: debugData.logs.notice
        },
        {
            titleKey: 'logs_section.other_log',
            content: debugData.logs.other
        },
        {
            titleKey: 'logs_section.custom_log',
            content: debugData.logs.custom
        }
    ]

    return (
        <div className="section-background">
            <div className="section-title">
                <FontAwesomeIcon icon={faFilePen} /> { t('logs_section.logs') }
            </div>
            <div className="section-content mx-4 gap-y-4">
                {logs.map((log, idx) => (
                    <div key={idx}>
                        <p className="text-normal text-left pl-4 font-medium">{ t(log.titleKey) }</p>
                        <SyntaxHighlighter className="log-content" language="accesslog" wrapLongLines={true} style={theme === 'light' ? githubGist : githubDarkDimmed as any}>
                            {log.content.length > 0 ? log.content : t('logs_section.empty_log')}
                        </SyntaxHighlighter>
                    </div>
                ))}
            </div>
        </div>
    );
}

export default LogsSection;

// src/components/sections/LogsSection.vue
<template>
  <div class="section-background">
    <div class="section-title">
      <font-awesome-icon icon="file-pen"/> {{ $t('logs_section.logs') }}
    </div>
    <div class="section-content grid grid-cols-1 gap-y-4">
      <div v-for="(content, type) of data.logs" :key="type">
        <p class="text-normal text-left pl-4 font-medium">{{ $t(`logs_section.${type}_log`) }}</p>
        <highlightjs
            class="log-content"
            language="log"
            :code="content ? content : $t('logs_section.empty_log')"
        />
      </div>
    </div>
  </div>
</template>

<script>
import hljs from 'highlight.js/lib/core';
import log from 'highlight.js/lib/languages/accesslog';
import hljsVuePlugin from "@highlightjs/vue-plugin";
import 'highlight.js/styles/github-dark-dimmed.css';

export default {
  props: [
    'data',
  ],
  components: {
    highlightjs: hljsVuePlugin.component
  },
  beforeMount() {
    hljs.registerLanguage('log', log);
  }
}
</script>
