// src/components/sections/VersionSection.tsx
import SimpleSection from "../SimpleSection";
import {SectionContent} from "../../types/SectionContent";
import {DebugData} from "../../types/DebugData";
import {useTranslation} from "react-i18next";
import {asCode, booleanBadge, formatDate} from "../../utils";
import {faDownload} from "@fortawesome/free-solid-svg-icons";

interface Props {
    debugData: DebugData;
}

function VersionSection({
    debugData, // Hook for this?
}: Props) {

    const { t } = useTranslation();

    const content: SectionContent[] = [
        {
            header: t('version_section.version'),
            body: asCode(debugData.namelessmc.version),
        },
        {
            header: t('version_section.update_available'),
            body: booleanBadge(debugData.namelessmc.update_available, true),
        },
        {
            header: t('version_section.last_update_check'),
            body: `<h2 class="text-normal">${formatDate(debugData.namelessmc.update_checked)}</h2>`,
        },
    ]

    return (
        <SimpleSection icon={faDownload} titleKey={'version_section.version'} content={content} />
    )
}

export default VersionSection;

// src/components/sections/VersionSection.vue
<template>
    <div class="section-background">
        <div class="section-title">
            <font-awesome-icon icon="download"/> {{ $t('version_section.version') }}
        </div>
        <div class="section-content grid-cols-3">
            <div>
                <h5 class="section-heading">{{ $t('version_section.version') }}</h5>
                <h2 v-html="asCode(data.namelessmc.version)"></h2>
            </div>
            <div>
                <h5 class="section-heading">{{ $t('version_section.update_available') }}</h5>
                <h5 v-html="booleanBadge(data.namelessmc.update_available, true)"></h5>
            </div>
            <div>
                <h5 class="section-heading">{{ $t('version_section.last_update_check') }}</h5>
                <h2 class="text-normal">{{ formatDate(data.namelessmc.update_checked) }}</h2>
            </div>
        </div>
    </div>
</template>

<script>
export default {
    props: [
        'data',
    ],
}
</script>
