// src/components/sections/WebhooksSection.tsx
import {DebugData} from "../../types/DebugData";
import FloatingSection, {FloatingContent} from "../FloatingSection";
import {faLink} from "@fortawesome/free-solid-svg-icons";
import {asCode} from "../../utils";

interface Props {
    debugData: DebugData;
}

function WebhooksSection({
    debugData,
}: Props) {

    const actionFromId = (actionId: number): string => {
        for (const [id, name] of Object.entries(debugData.namelessmc.settings.webhooks.actions)) {
            if (String(actionId) === id) {
                return name;
            }
        }

        return 'unknown';
    }

    const hooksFloatingContent: FloatingContent = {
        subheadingKey: 'webhooks_section.hooks',
        table: {
            columnHeaders: [
                {
                    key: 'webhooks_section.id',
                    classes: ['w-1/6'],
                },
                {
                    key: 'webhooks_section.name',
                },
                {
                    key: 'webhooks_section.type',
                },
                {
                    key: 'webhooks_section.events',
                }
            ],
            rows: Object.values(debugData.namelessmc.settings.webhooks.hooks).map(hook => {
                return {
                    cells: [
                        {
                            body: String(hook.id),
                        },
                        {
                            body: hook.name,
                        },
                        {
                            body: actionFromId(hook.action),
                        },
                        {
                            body: asCode(hook.events.join('\n')),
                        }
                    ],
                }
            }),
            emptyState: {
                textKey: 'webhooks_section.no_hooks',
            }
        }
    }

    const hookById = (hookId: number) => {
        for (const [id, hook] of Object.entries(debugData.namelessmc.settings.webhooks.hooks)) {
            if (String(hookId) === id) {
                return hook.name;
            }
        }

        return 'unknown';
    }

    const forumHooksFloatingContent: FloatingContent = {
        subheadingKey: 'webhooks_section.forum_hooks',
        table: {
            columnHeaders: [
                {
                    key: 'webhooks_section.forum_id',
                    classes: ['w-1/6'],
                },
                {
                    key: 'webhooks_section.forum_title',
                },
                {
                    key: 'webhooks_section.hooks',
                }
            ],
            rows: Object.values(debugData.namelessmc.settings.webhooks.forum_hooks).map(hook => {
                return {
                    cells: [
                        {
                            body: String(hook.forum_id),
                        },
                        {
                            body: hook.title,
                        },
                        {
                            body: asCode(hook.hooks.map(h => hookById(h)).join('\n')),
                        }
                    ]
                }
            }),
            emptyState: {
                textKey: "webhooks_section.no_forum_hooks"
            }
        }
    }

    return (
        <FloatingSection icon={faLink} titleKey={'webhooks_section.webhooks'} floatingContent={[hooksFloatingContent, forumHooksFloatingContent]} />
    )
}

export default WebhooksSection;

// src/components/sections/WebhooksSection.vue
<template>
      <div class="section-title-floating">
          <font-awesome-icon icon="link"/> {{ $t('webhooks_section.webhooks') }}
      </div>
      <div class="pt-2 mb-8 grid gap-4 lg:grid-cols-2 md:grid-cols-1">
          <div class="section-content-floating">
              <h3 class="section-subheading">{{ $t('webhooks_section.hooks') }}</h3>
              <table class="table-container">
                  <tr>
                      <th class="table-title w-1/6">{{ $t('webhooks_section.id') }}</th>
                      <th class="table-title">{{ $t('webhooks_section.name') }}</th>
                      <th class="table-title">{{ $t('webhooks_section.type') }}</th>
                      <th class="table-title">{{ $t('webhooks_section.events') }}</th>
                  </tr>
                  <template v-if="Object.keys(this.data.namelessmc.settings.webhooks.hooks).length > 0">
                      <tr v-for="hook in this.data.namelessmc.settings.webhooks.hooks" :key="hook">
                        <td class="table-data">{{ hook.id }}</td>
                        <td class="table-data">{{ hook.name }}</td>
                        <td class="table-data">{{ this.getTypeById(hook.action) }}</td>
                        <td class="table-data">
                            <p v-for="event in hook.events" :key="event" v-html="asCode(event)"></p>
                        </td>
                      </tr>
                  </template>
                  <tr v-else>
                      <td class="table-data" colspan="4">
                          <i>{{ $t('webhooks_section.no_hooks') }}</i>
                      </td>
                  </tr>
              </table>
          </div>
          <div class="section-content-floating">
              <h3 class="section-subheading">{{ $t('webhooks_section.forum_hooks') }}</h3>
              <table class="table-container">
                  <tr>
                      <th class="table-title w-1/6">{{ $t('webhooks_section.forum_id') }}</th>
                      <th class="table-title">{{ $t('webhooks_section.forum_title') }}</th>
                      <th class="table-title">{{ $t('webhooks_section.hooks') }}</th>
                  </tr>
                  <template v-if="this.data.namelessmc.settings.webhooks.forum_hooks.length > 0">
                      <tr v-for="forum_hook in this.data.namelessmc.settings.webhooks.forum_hooks" :key="forum_hook">
                          <td class="table-data">{{ forum_hook.forum_id }}</td>
                          <td class="table-data">{{ forum_hook.title }}</td>
                          <td class="table-data">
                              <p v-for="hook in forum_hook.hooks" :key="hook" v-html="asCode(this.getHookNameById(hook))"></p>
                          </td>
                      </tr>
                  </template>
                  <tr v-else>
                      <td class="table-data" colspan="3">
                          <i>{{ $t('webhooks_section.no_forum_hooks') }}</i>
                      </td>
                  </tr>
              </table>
          </div>
      </div>
</template>

<script>
export default {
    props: [
        'data',
    ],
    methods: {
        getTypeById(id) {
            return this.data.namelessmc.settings.webhooks.actions[id];
        },
        getHookNameById(id) {
            return this.data.namelessmc.settings.webhooks.hooks[id].name;
        },
    },
}
</script>
